# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CanKahraman
                                 A QGIS plugin
 this This plugin locates MEB schools.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-12
        copyright            : (C) 2025 by MUGLA SITKI KOCMAN UNIVERSITY
        email                : cankahraman017@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CanKahraman class from file CanKahraman.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .can_kahraman import CanKahraman
    return CanKahraman(iface)
